# playbooks/trigger_servicenow_api.yml
---
- name: Fetch Change Requests for a CI from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "dev12345"
    servicenow_user: "admin"
    servicenow_password: "admin_password"
    ci_name: "CI12345"  # Provide the CI name for filtering change requests

  roles:
    - servicenow_api
